# Emplacement du cache (interne au conteneur)
CacheDir: /var/cache/apt-cacher-ng

# Port d'écoute
Port: 3142

# CONFIGURATION PROXY AMONT (Ton Squid)
# On utilise l'IP directe car ACNG gère son propre accès réseau
Proxy: http://172.16.0.1:3128

# OPTIMISATIONS PERFORMANCE LABO
MaxThreads: 100
KeepAliveIdle: 60
NetworkTimeout: 60

# REMAPPING (Le "Cœur" de l'efficacité)
# Utilise les fichiers de miroirs par défaut
Remap-debrep: file:deb_mirror*.gz /debian ; file:backends_debian
Remap-uburep: file:ubuntu_mirrors /ubuntu ; file:backends_ubuntu

# GESTION DU HTTPS (Pass-through pour Docker/VSCode)
PassThroughPattern: .*

# RÉGLAGES DE MAINTENANCE
ReportPage: acng-report.html
# Autorise l'effacement via l'interface web si besoin
AdminPassword: ton_mot_de_passe_admin